name: Update pinned Python dependencies for the actions

on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.11'

      - run: pip install pip-tools

      - run: |
          echo "TEST googleapis-common-protos"
          echo "googleapis-common-protos" > test.txt.in
          pip-compile --strip-extras --upgrade test.txt.in 2>&1 | grep "googleapis-common-protos=="

          echo "TEST googleapis-common-protos[grpc]<2.0.0dev,>=1.56.0"
          echo "googleapis-common-protos[grpc]<2.0.0dev,>=1.56.0" > test.txt.in
          pip-compile --strip-extras --upgrade test.txt.in 2>&1 | grep "googleapis-common-protos=="

          echo "TEST googleapis-common-protos[grpc]"
          echo "googleapis-common-protos[grpc]" > test.txt.in
          pip-compile --strip-extras --upgrade test.txt.in 2>&1 | grep "googleapis-common-protos=="

          echo "TEST googleapis-common-protos[grpc]<2.0.0dev"
          echo "googleapis-common-protos[grpc]<2.0.0dev" > test.txt.in
          pip-compile --strip-extras --upgrade test.txt.in 2>&1 | grep "googleapis-common-protos=="

